"""The manuscript can build cleanly and still be wrong on the page.

Two failures of 2026-09-15 are pinned here, because neither raises a LaTeX
error and neither is visible in the source:

  Table 12 overran its column by 102pt. Its cells were placeholders, and
  "[pending]" is nine characters where the number it stands for is five, so
  every table was typeset to the width of the placeholder rather than of the
  data.

  Worse, those cells were `\\num{}` -- an EMPTY macro name. \\num falls back to
  \\PENDING when the name is not defined, so an empty one can never be filled by
  anything. The backbone runs could all finish and the table would stay red,
  indistinguishable from one still waiting for data.
"""
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
TEX = ROOT / "paper" / "steerf.tex"
LOG = ROOT / "paper" / "steerf.log"
NUMBERS = ROOT / "results" / "numbers.tex"

# An overfull box this small is invisible on the page; LaTeX reports them for
# almost any justified paragraph.
OVERFULL_PT = 5.0


@pytest.fixture(scope="module")
def tex():
    if not TEX.is_file():
        pytest.skip("the manuscript is not in this checkout")
    return TEX.read_text()


def test_no_slot_is_unfillable(tex):
    """`\\num{}` names nothing, so nothing can ever fill it."""
    empty = re.findall(r"\\num\{\s*\}", tex)
    assert not empty, f"{len(empty)} slot(s) with an empty macro name"


def test_every_slot_names_a_legal_macro(tex):
    """\\csname needs letters; a slot with digits or punctuation cannot resolve."""
    bad = [n for n in re.findall(r"\\num\{([^}]*)\}", tex) if not re.fullmatch(r"[A-Za-z]+", n)]
    assert not bad, f"slots whose name is not a legal macro: {bad}"


def test_the_placeholder_is_not_wider_than_a_number(tex):
    """A table sized by its placeholder is not a preview of the final table."""
    m = re.search(r"\\providecommand\{\\PENDING\}\{(.*)\}\s*$", tex, re.M)
    assert m, "PENDING is not defined"
    visible = re.sub(r"\\[a-zA-Z]+|[{}]", "", m.group(1))
    assert len(visible) <= len(".1495"), \
        f"PENDING renders as {visible!r}, wider than the number it stands for"
    assert "red" in m.group(1), "an unmeasured number must still be loud"


def test_a_filled_slot_is_a_real_measurement(tex):
    """Whatever numbers.tex defines has to come from the log analysis."""
    if not NUMBERS.is_file():
        pytest.skip("results/numbers.tex has not been generated")
    head = NUMBERS.read_text()[:500]
    assert "generated by scripts/analyze_seeds.py" in head, \
        "numbers.tex must be generated, never hand-edited"


# --------------------------------------------------------------- the build
def test_nothing_overflows_its_column():
    if not LOG.is_file():
        pytest.skip("no build log; run pdflatex in paper/ first")
    over = [float(m) for m in
            re.findall(r"Overfull \\hbox \(([0-9.]+)pt too wide\)", LOG.read_text(errors="replace"))]
    bad = [pt for pt in over if pt > OVERFULL_PT]
    assert not bad, f"overfull by {bad} pt -- a table is running into the next column"


def test_the_build_resolves_every_reference():
    if not LOG.is_file():
        pytest.skip("no build log; run pdflatex in paper/ first")
    log = LOG.read_text(errors="replace")
    assert "Undefined control sequence" not in log
    assert not re.search(r"(Citation|Reference) `[^']*' on page .* undefined", log)
