"""The manuscript can build cleanly and still be wrong on the page.

Two failures of 2026-09-15 are pinned here, because neither raises a LaTeX
error and neither is visible in the source:

  Table 12 overran its column by 102pt. Its cells were placeholders, and
  "[pending]" is nine characters where the number it stands for is five, so
  every table was typeset to the width of the placeholder rather than of the
  data.

  Worse, those cells were `\\num{}` -- an EMPTY macro name. \\num falls back to
  \\PENDING when the name is not defined, so an empty one can never be filled by
  anything. The backbone runs could all finish and the table would stay red,
  indistinguishable from one still waiting for data.
"""
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
TEX = ROOT / "paper" / "steerf.tex"
LOG = ROOT / "paper" / "steerf.log"
NUMBERS = ROOT / "results" / "numbers.tex"

# An overfull box this small is invisible on the page; LaTeX reports them for
# almost any justified paragraph.
OVERFULL_PT = 5.0


@pytest.fixture(scope="module")
def tex():
    """The manuscript with its LaTeX comments removed.

    The header documents the slot mechanism with a literal `\\num{X}` example,
    and a comment is not a slot -- counting it made the audit report one
    permanently unfillable cell that does not exist.
    """
    if not TEX.is_file():
        pytest.skip("the manuscript is not in this checkout")
    return "\n".join(l for l in TEX.read_text().splitlines()
                      if not l.lstrip().startswith("%"))


def test_no_slot_is_unfillable(tex):
    """`\\num{}` names nothing, so nothing can ever fill it."""
    empty = re.findall(r"\\num\{\s*\}", tex)
    assert not empty, f"{len(empty)} slot(s) with an empty macro name"


def test_every_slot_names_a_legal_macro(tex):
    """\\csname needs letters; a slot with digits or punctuation cannot resolve."""
    bad = [n for n in re.findall(r"\\num\{([^}]*)\}", tex) if not re.fullmatch(r"[A-Za-z]+", n)]
    assert not bad, f"slots whose name is not a legal macro: {bad}"


def test_the_placeholder_is_not_wider_than_a_number(tex):
    """A table sized by its placeholder is not a preview of the final table."""
    m = re.search(r"\\providecommand\{\\PENDING\}\{(.*)\}\s*$", tex, re.M)
    assert m, "PENDING is not defined"
    visible = re.sub(r"\\[a-zA-Z]+|[{}]", "", m.group(1))
    assert len(visible) <= len(".1495"), \
        f"PENDING renders as {visible!r}, wider than the number it stands for"
    assert "red" in m.group(1), "an unmeasured number must still be loud"


def test_a_filled_slot_is_a_real_measurement(tex):
    """Whatever numbers.tex defines has to come from the log analysis."""
    if not NUMBERS.is_file():
        pytest.skip("results/numbers.tex has not been generated")
    head = NUMBERS.read_text()[:500]
    assert "generated by scripts/analyze_seeds.py" in head, \
        "numbers.tex must be generated, never hand-edited"


# --------------------------------------------------------------- the build
def test_nothing_overflows_its_column():
    if not LOG.is_file():
        pytest.skip("no build log; run pdflatex in paper/ first")
    over = [float(m) for m in
            re.findall(r"Overfull \\hbox \(([0-9.]+)pt too wide\)", LOG.read_text(errors="replace"))]
    bad = [pt for pt in over if pt > OVERFULL_PT]
    assert not bad, f"overfull by {bad} pt -- a table is running into the next column"


def test_the_build_resolves_every_reference():
    if not LOG.is_file():
        pytest.skip("no build log; run pdflatex in paper/ first")
    log = LOG.read_text(errors="replace")
    assert "Undefined control sequence" not in log
    assert not re.search(r"(Citation|Reference) `[^']*' on page .* undefined", log)


# --------------------------------------- can a finished experiment reach the page?
def emittable_names():
    """Every macro name scripts/analyze_seeds.py is able to write.

    Derived from the source rather than from a list kept here, so the two
    cannot drift: a slot the manuscript asks for and the emitter cannot produce
    is a table that stays red however long its experiment runs.
    """
    src = (ROOT / "scripts" / "analyze_seeds.py").read_text()
    arms = re.search(r"MAIN_ARMS = \[([^\]]*)\]", src).group(1)
    arms = re.findall(r'"([a-z-]+)"', arms)
    stems = re.findall(r'"[a-z0-9.-]+":\s*"([a-z]+)"', src)
    metrics = ["acc", "maj", "uplift", "entropy"]
    pairs = re.findall(r'\("([a-z]+)", "([a-z]+)"\)', src)

    names = {"Nseeds", "Plateaulo", "Plateauhi", "STDaime", "SEaime", "Wseed",
             "Bsigncount", "Dirconsistency", "Dirconsistencyperm",
             "Matchstep", "Longsteps", "Rgrpolongacc",
             "Wsigned", "Wgrpo", "Wgrpolong"}
    for a in arms:
        names |= {f"N{a}", f"Nall{a}", f"R{a}len", f"R{a}cost"}
        for c in metrics:
            names |= {f"R{a}{c}", f"E{a}{c}", f"S{a}{c}", f"Lo{a}{c}", f"Hi{a}{c}"}
    for stem in stems:
        names |= {f"R{stem}{c}" for c in ("acc", "maj", "uplift")}
    for a, b in pairs:
        for c in metrics:
            names |= {f"C{a}{b}{c}", f"T{a}{b}{c}", f"P{a}{b}{c}",
                      f"W{a}{b}{c}", f"WT{a}{b}{c}", f"WN{a}{b}{c}"}
        names.add(f"N{a}{b}")
    # The locality measurement has its own emitter; read its table rather
    # than listing the names here, for the same reason as above.
    loc = (ROOT / "scripts" / "emit_locality_numbers.py").read_text()
    body = re.search(r"MACROS = \{(.*?)\n\}", loc, re.S)
    names |= set(re.findall(r'"([A-Za-z]+)":\s*\(', body.group(1)))
    names |= set(re.findall(r'out\["([A-Za-z]+)"\]', loc))

    # backbone rows are the same analysis under --macro-prefix
    prefixed = set()
    for pre in ("Bqwenbig", "Bllama", "Bmistral"):
        prefixed |= {pre + n for n in names}

    # The go/no-go probes carry their own full names rather than a prefix, so
    # they join after the prefixing rather than before it. Same rule as above:
    # read the emitter's table, do not restate it here.
    probe = (ROOT / "scripts" / "emit_probe_numbers.py").read_text()
    body = re.search(r"MACROS = \{(.*?)\n\}", probe, re.S)
    extra = set(re.findall(r'"([A-Za-z]+)":\s*\(', body.group(1)))
    extra |= set(re.findall(r'out\["([A-Za-z]+)"\]', probe))
    extra |= set(re.findall(r'"([A-Za-z]+)"', re.search(
        r"PASSRATE_MACROS = \{([^}]*)\}", probe).group(1)))

    return names | prefixed | extra


def test_every_slot_can_be_produced_by_the_emitter(tex):
    """The generalisation of the Table 12 defect.

    There, twenty cells had no macro name at all. Here the names exist but
    nothing writes them: until 2026-09-15 analyze_seeds.py knew only the five
    main arms, so the follow-up ablations, the compute-matched control, the
    backbones and the six-benchmark count could all finish and leave their
    tables red, indistinguishable from tables still waiting for data.
    """
    want = set(re.findall(r"\\num\{([A-Za-z]+)\}", tex))
    orphans = sorted(want - emittable_names())
    assert not orphans, (
        f"{len(orphans)} slot(s) no run can ever fill: {orphans[:12]}")
