#!/usr/bin/env python3
# Copyright 2026 STEER-F authors
# Licensed under the Apache License, Version 2.0
"""Turn the backbone go/no-go probes into the manuscript's \\num{} macros.

    python3 scripts/emit_probe_numbers.py \
        --json          docs/backbone_probe.json \
        --passrate-ref  docs/probe_qwen15.json \
        --passrate-new  docs/probe_llama32i.json \
        --out           results/numbers-probe.tex

WHY THIS EXISTS
    Section 11.1 has to say why one backbone row uses an instruction-tuned
    checkpoint while the others use base ones.  "It scored near zero" is a
    claim, and the manuscript's rule is that a claim carrying a number gets
    that number from a generator, never from a hand-typed literal -- the
    defect fixed on 2026-09-15, where `\\num{0.145}` passed a literal to a
    macro lookup and rendered as a placeholder.

    It is a separate emitter from emit_locality_numbers.py rather than a
    second table inside it because the two read different JSON schemas, and
    because a probe is a pre-registration artefact: it is written before the
    run it gates, and it stays in the record whether the run happens or not.

WHAT IT EMITS
    `Bllamabaseacc` / `Bllamabasegsm` are the base checkpoint's scores, the
    measurement that rejected it.  GSM8K is there on purpose: MATH500 near
    zero reads as "hard benchmark", but grade-school arithmetic near zero
    reads as what it is, a model that never emits an answer.

    `Bqweninform` / `Bllamainform` / `Bllamainformratio` are the gate proper
    -- the fraction of GRPO groups that are not degenerate, for a backbone
    known to train and for the candidate.  The ratio is what the prose
    quotes, because the tool's grader is not the training reward and its
    absolute value is therefore not a reward rate.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

# macro stem -> (section, key path, format).  tests/test_paper.py reads this
# table to decide which slots a run can fill, so a name added here is a name
# the manuscript is allowed to ask for.
MACROS = {
    "Bllamabaseacc": ("llama_base_eval", ("avg_at_1", "math500"), "acc"),
    "Bllamabasegsm": ("llama_base_eval", ("avg_at_1", "gsm8k_test"), "acc"),
}

# The two passrate files arrive from scripts/phase3_port_model.py --out, so
# they are read as whole documents rather than through the table above.
PASSRATE_MACROS = {"Bqweninform", "Bllamainform", "Bllamainformratio"}


def fmt(value, how):
    if how == "acc":
        return f"{float(value):.3f}"
    return f"{float(value):.3f}"


def dig(doc, path):
    for key in path:
        if not isinstance(doc, dict) or key not in doc:
            return None
        doc = doc[key]
    return doc


def emit(doc, ref=None, new=None):
    """macro name -> rendered value, skipping anything not yet measured."""
    out = {}
    for name, (section, path, how) in MACROS.items():
        value = dig(doc.get(section) or {}, path)
        if value is None:
            continue              # stays \PENDING: a red cell, not a lie
        try:
            out[name] = fmt(value, how)
        except (TypeError, ValueError):
            continue

    # Either passrate file may be absent -- the probe is run on the box, and
    # the manuscript should show a red cell until it is, not a guess.
    ref_frac = (ref or {}).get("informative_frac")
    new_frac = (new or {}).get("informative_frac")
    if isinstance(ref_frac, (int, float)):
        out["Bqweninform"] = f"{float(ref_frac):.3f}"
    if isinstance(new_frac, (int, float)):
        out["Bllamainform"] = f"{float(new_frac):.3f}"
    if isinstance(ref_frac, (int, float)) and isinstance(new_frac, (int, float)) and ref_frac:
        out["Bllamainformratio"] = f"{new_frac / ref_frac:.2f}"
    return out


def load(path):
    p = Path(path) if path else None
    if p is None or not p.is_file():
        return None
    return json.loads(p.read_text())


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--json", default="docs/backbone_probe.json")
    p.add_argument("--passrate-ref", default="docs/probe_qwen15.json")
    p.add_argument("--passrate-new", default="docs/probe_llama32i.json")
    p.add_argument("--out", default="results/numbers-probe.tex")
    args = p.parse_args(argv)

    src = Path(args.json)
    if not src.is_file():
        print(f"[probe-macros] no {src} -- nothing to emit.")
        return 1

    values = emit(json.loads(src.read_text()),
                  load(args.passrate_ref), load(args.passrate_new))
    lines = ["% generated by scripts/emit_probe_numbers.py -- do not edit",
             f"% source: {args.json}"]
    lines += [f"\\providecommand{{\\{k}}}{{{v}}}" for k, v in sorted(values.items())]

    dest = Path(args.out)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines) + "\n")

    missing = sorted((set(MACROS) | PASSRATE_MACROS) - set(values))
    print(f"[probe-macros] {len(values)} macros -> {dest}")
    if missing:
        print(f"[probe-macros] not measured yet, left red: {missing}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
