#!/usr/bin/env python3
# Copyright 2026 STEER-F authors
# Licensed under the Apache License, Version 2.0
"""Turn a forecast-locality JSON into the manuscript's \\num{} macros.

    python3 scripts/emit_locality_numbers.py \
        --json docs/forecast_locality_val.json \
        --out  results/numbers-locality.tex

WHY THIS EXISTS
    `scripts/measure_forecast_locality.py` answers the sharpest objection to
    the paper -- with an effective horizon of one step, is `A_H` anything a
    purely local quantity could not have produced?  Its answer belongs in the
    manuscript, and the manuscript's rule is that no measured number is typed
    by hand: Section 12's cells are `\\num{<name>}` and a generator writes the
    name.  Typing these eight would repeat exactly the defect fixed on
    2026-09-15, where `\\num{0.145}` passed a literal to a macro lookup and
    three sentences rendered as placeholders.

WHAT IT EMITS
    The branch-point scope is the headline -- `A_H` is identically zero
    outside it, so the wider sibling-support scope dilutes every statistic
    with exact zeros.  Both are emitted; the paper quotes the branch points
    and reports the support count for context.

    `Locahmag` and `Locloctwinmag` are the non-degeneracy check.  A near-zero
    correlation means "the two signals are unrelated" only if both signals
    exist; if the local twin were numerical dust it would correlate with
    nothing at all and the test would be vacuous.  The two magnitudes let a
    reader rule that out, so they are emitted even though the prose quotes
    them only once.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

BRANCH, SUPPORT = "branch_points_only", "sibling_support"

# macro stem -> (scope, json key, format).  tests/test_paper.py reads this
# table to decide which slots a run can fill, so a name added here is a name
# the manuscript is allowed to ask for -- and one removed here fails the
# orphan check instead of silently leaving a red cell.
MACROS = {
    "Locn":             (BRANCH,  "n_positions", "int"),
    "Locnsupport":      (SUPPORT, "n_positions", "int"),
    "Loclevels":        (BRANCH,  "levels_pearson_h_togo_vs_h_local", "corr"),
    "Loclevelsrho":     (BRANCH,  "levels_spearman_h_togo_vs_h_local", "corr"),
    "Loclevelssupport": (SUPPORT, "levels_pearson_h_togo_vs_h_local", "corr"),
    "Locadv":           (BRANCH,  "advantage_pearson_a_h_vs_a_local", "corr"),
    "Locadvrho":        (BRANCH,  "advantage_spearman_a_h_vs_a_local", "corr"),
    "Locadvsupport":    (SUPPORT, "advantage_pearson_a_h_vs_a_local", "corr"),
    "Locrsq":           (BRANCH,  "advantage_r_squared", "plain"),
    "Locsign":          (BRANCH,  "sign_agreement", "plain"),
    "Locahmag":         (BRANCH,  "a_h_absmean", "mag"),
    "Locloctwinmag":    (BRANCH,  "a_local_absmean", "mag"),
}


def fmt(value, how):
    if how == "int":
        return str(int(value))
    if how == "corr":                 # sign carries the meaning here
        return f"{float(value):+.3f}"
    if how == "mag":
        return f"{float(value):.4f}"
    return f"{float(value):.3f}"


def emit(doc):
    """macro name -> rendered value, skipping anything the run did not reach."""
    out = {}
    for name, (scope, key, how) in MACROS.items():
        block = doc.get(scope) or {}
        if key not in block:
            continue                  # stays \PENDING: a red cell, not a lie
        try:
            out[name] = fmt(block[key], how)
        except (TypeError, ValueError):
            continue
    cfg = doc.get("config") or {}
    if "n_groups" in cfg:
        out["Locgroups"] = str(int(cfg["n_groups"]))
    # Derived, because the prose's whole point is that this ratio lands on the
    # calibration constant gamma_H * a_1 = .72 rather than on 1.
    b = doc.get(BRANCH) or {}
    if b.get("a_local_absmean"):
        out["Locratio"] = f"{b['a_h_absmean'] / b['a_local_absmean']:.3f}"
    return out


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--json", default="docs/forecast_locality_val.json")
    p.add_argument("--out", default="results/numbers-locality.tex")
    args = p.parse_args(argv)

    src = Path(args.json)
    if not src.is_file():
        print(f"[locality-macros] no {src} -- nothing to emit. Run "
              f"scripts/measure_forecast_locality.py first.")
        return 1

    values = emit(json.loads(src.read_text()))
    lines = ["% generated by scripts/emit_locality_numbers.py -- do not edit",
             f"% source: {args.json}"]
    lines += [f"\\providecommand{{\\{k}}}{{{v}}}" for k, v in sorted(values.items())]

    dest = Path(args.out)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines) + "\n")

    missing = sorted(set(MACROS) - set(values))
    print(f"[locality-macros] {len(values)} macros -> {dest}")
    if missing:
        print(f"[locality-macros] not in the JSON, left red: {missing}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
